dependencies:
  - name: postgresql
    version: 3.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
    alias: postgres
    condition: postgres.enabled
  - name: redis
    version: 5.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled
